### ISSUE TITLE
how to use frida to reflect a method 

### ISSUE THREAD

**Issue by zxhubo** [0xdea/frida-scripts#2]
For example, a java function 
```
public byte[] aesEncrypt(String plaintext)
```
I want to reflect this method,

```
 var class_name1 = "com.example.cryptutils.util.CryptoUtils";
  var Platform1  = Java.use(class_name1);
var method = Platform1.getDeclaredMethod("aesEncrypt",XXXXX);
```
how to input the XXXX ?

**Comment by 0xdea** [comment]
Hi, not sure I understand your question. However, you should refer to Frida's documentation and examples, e.g.:

https://github.com/frida/frida-java
https://github.com/iddoeldor/frida-snippets
https://codeshare.frida.re/@dzonerzy/dereflector/

If you still have doubts I suggest you to contact https://telegram.me/fridadotre directly.
