### ISSUE TITLE
Lots of undefined printed out in enum

### ISSUE THREAD

**Issue by mustafairan** [0xdea/frida-scripts#9]
I think that catch needs a return; statement. When I try to enumerate all classes , it prints lots of undefined because you push null values to the allclasses eventhough it catches an error	

	classes.forEach(function(aClass) {
		try {
			var className = aClass.match(/[L](.*);/)[1].replace(/\//g, ".");
		}
		catch(err) {} // avoid TypeError: cannot read property 1 of null
		allClasses.push(className);
	});
I think needs to be

	classes.forEach(function(aClass) {
		try {
			var className = aClass.match(/[L](.*);/)[1].replace(/\//g, ".");
		}
		catch(err) {return;} // avoid TypeError: cannot read property 1 of null
		allClasses.push(className);
	});

**Comment by 0xdea** [comment]
Hi, thank you for reporting this issue. I'll accept your pull request. However, I don't use these scripts much anymore, so they probably need an overhaul to work with modern mobile apps/OSes. You may want to take a look at this project, which includes some of my scripts and keeps them up to date: https://github.com/federicodotta/Brida

**Comment by mustafairan** [comment]
Hi, Thanks for the reply. I already aware of brida and used the old version of it. It's very nice tool but the new version of the plugin is a little bit complicated. Also, I try to go manuel a bit. Thanks anyway for the suggestion
